export const OVERVIEW_COLUMN_WIDTH = 75
export const OVERVIEW_COLUMN_PADDING_X = 6
export const CONTENT_COLUMN_PADDING_X = 8
export const IMAGE_WIDTH = 50
export const IMAGE_HEIGHT = 50
export const IMAGE_MARGIN_LEFT = (OVERVIEW_COLUMN_WIDTH - IMAGE_WIDTH) / 2
export const IMAGE_MARGIN_RIGHT = IMAGE_MARGIN_LEFT + CONTENT_COLUMN_PADDING_X
export const HEADER_PADDING_TOP = 20
export const HEADER_PADDING_BOTTOM = 8
export const HEADER_HEIGHT =
  IMAGE_HEIGHT + HEADER_PADDING_TOP + HEADER_PADDING_BOTTOM
